# Generated by Django 2.1.3 on 2018-11-12 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TreatmentPlant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.IntegerField()),
                ('fruits_vegetables', models.FloatField()),
                ('edible_starchy', models.FloatField()),
                ('edible_animal', models.FloatField()),
                ('disp_infant_nappies', models.IntegerField()),
                ('disp_adult_nappies', models.IntegerField()),
                ('sap', models.FloatField()),
                ('plastics', models.FloatField()),
                ('compost', models.FloatField()),
                ('biogas_stp', models.FloatField()),
                ('thermal_energy_equivalent', models.FloatField()),
            ],
        ),
    ]
