# Generated by Django 2.1.3 on 2018-11-15 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatment_plants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnbioTreatmentPlant',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False, verbose_name='Date')),
                ('weight_hfw_morning', models.IntegerField(verbose_name='Weight of HFW (kg)(MORNING)')),
                ('weight_forbi_morning', models.IntegerField(verbose_name='Weight of FORBI (kg) (MORNING)')),
                ('electricity_ci_start_morning', models.FloatField(verbose_name='Electricity counter index (start of every cycle) (kW)(MORNING)')),
                ('electricity_ci_end_morning', models.FloatField(verbose_name='Electricity counter index (end of every cycle) (kW)(MORNING)')),
                ('energy_consumption_morning', models.FloatField(verbose_name='Energy consumption (kW) (MORNING)')),
                ('weight_hfw_afternoon', models.IntegerField(verbose_name='Weight of HFW (kg)(AFTERNOON)')),
                ('weight_forbi_afternoon', models.IntegerField(verbose_name='Weight of FORBI (kg) (AFTERNOON)')),
                ('electricity_ci_start_afternoon', models.FloatField(verbose_name='Electricity counter index (start of every cycle) (kW)(AFTERNOON)')),
                ('electricity_ci_end_afternoon', models.FloatField(verbose_name='Electricity counter index (end of every cycle) (kW)(AFTERNOON)')),
                ('energy_consumption_afternoon', models.FloatField(verbose_name='Energy consumption (kW) (AFTERNOON)')),
            ],
        ),
        migrations.CreateModel(
            name='GreenTechTreatmentPlant',
            fields=[
                ('week', models.IntegerField(primary_key=True, serialize=False, verbose_name='Week[#]')),
                ('fruits_vegetables', models.FloatField(verbose_name='Fruits and vegetables [kg]')),
                ('edible_starchy', models.FloatField(verbose_name='Edible starchy products [kg]')),
                ('edible_animal', models.FloatField(verbose_name='Edible animal products/byproducts [kg]')),
                ('disp_infant_nappies', models.IntegerField(verbose_name='Used, disposable infant nappies [#]')),
                ('disp_adult_nappies', models.IntegerField(verbose_name='Used, disposable adult nappies [#]')),
                ('sap', models.FloatField(verbose_name='SAP [Kg]')),
                ('plastics', models.FloatField(verbose_name='Plastics [Kg]')),
                ('compost', models.FloatField(verbose_name='Compost [Kg]')),
                ('biogas_stp', models.FloatField(verbose_name='Biogas STP [L]')),
                ('thermal_energy_equivalent', models.FloatField(verbose_name='Thermal energy equivalent [MJ]')),
            ],
        ),
        migrations.DeleteModel(
            name='TreatmentPlant',
        ),
    ]
